#!/bin/bash

gcc -std=c99 -D_GNU_SOURCE otp_enc.c -o otp_enc
gcc -std=c99 -D_GNU_SOURCE otp_enc_d.c -o otp_enc_d
gcc -std=c99 -D_GNU_SOURCE otp_dec.c -o otp_dec
gcc -std=c99 -D_GNU_SOURCE otp_dec_d.c -o otp_dec_d
gcc -std=c99 -D_GNU_SOURCE keygen.c -o keygen
